---
title: "Privacy notice"
date: 2026-02-06
date-modified: last-modified
---

The Civil Service People Survey Explorer website is developed and maintained by
[Matt Kerlogue](https://matt.kerlogue.co.uk). This privacy notice explains how
personal information is used.

## What data is collected

Your personal data is only collected if you contact us by using the contact
form, by emailing us or raising an issue on Github.

We collect only your questions, queries or feedback, including your email
address or Github username (depending on the method used to contact us).

This website does not use cookies or collect any other forms of personal
information.

## Why we collect your data

Your personal data is collected gather feedback and respond to questions.

## The legal basis for processing your data 

The legal basis for processing your data is your consent, by contacting us
you consent to our use of your personal data so that we can respond to your
questions or feedback. In addition to your consent we also have a legitimate
interest in collecting and processing your personal data so that we can respond
to your questions or feedback.

## What we do with your data

We use the data you provide to respond to your questions and use feedback to
improve this website.

We will never sell your data to third parties. We will never share your data
to third parties for marketing or commercial purposes.

## How long we keep your data

We will only retain your personal data for as long as it is needed for the
purposes set out in this document or for as long as the law requires us to.

We will keep your feedback for up to 2 years.

## Where your data is processed and stored

If using the contact form or email then your data is collected and processed
using Microsoft 365, as far as is possible this data is located within
Microsoft's UK-based data centres. As a cloud based software service some data
may be stored in Microsoft cloud locations outside of the UK, in which case
the International Data Transfer Agreement (IDTA) is used to safeguard your
data.

## Links to other websites

This website contains links to other websites. This privacy notice applies
only to this website.

## Your rights

You have the following rights:

* The 'right of access' - You have the right to ask for copies of your personal
  information.
* The 'right to rectification' - You have the right to ask us to correct or
  delete personal information that you think is inaccurate or incomplete data.
* The 'right to erasure' - You have the right to ask us to delete your personal
  information.
* The 'right to restrict processing' - You have the right to ask us to limit
  how we can use your personal information.
* The 'right to object to processing' - You have the right to ask us to object
  to the processing of your personal data.
* The 'right to data portability' - You have the right to ask that we transfer
  the personal data you gave us to somebody else.
* The 'right to withdraw consent' - You have the right to withdraw your consent
  for us to continue processing or using your personal information.

You can read more about your rights on the
[ICO website](https://ico.org.uk/for-the-public/).

If you wish to exercise any of these rights please contact us using the
contact details in the section below.

## Contact us

If you have a question about anything in this privacy notice, think that your
data has been misused or mishandled, or wish to exercise any of your rights
then email us on <m@kerlogue.co.uk>.

## How to complain

If you have any concerns about our use of your personal data, you can make a
complaint to us using the contact details at the top of this privacy notice.

If you remain unhappy with how we’ve used your data after raising a complaint
with us, you can also complain to the ICO.

The ICO’s address:           

Information Commissioner’s Office  
Wycliffe House  
Water Lane  
Wilmslow  
Cheshire  
SK9 5AF

Helpline number: 0303 123 1113

Website: <https://www.ico.org.uk/make-a-complaint>

## Changes to this policy

We may change our privacy policy at any time and without notice. When the
policy changes the 'modified' date at the top of this page will reflect
when this policy has been changed. Any changes to this privacy policy will
apply to you and your data immediately.