---
title: "UK Civil Service benchmark results"
subtitle: |
    The benchmark (median) results for organisations participating in the
    UK Civil Service People Survey.
title-block-banner: true
toc-location: left
extensions:
    iconify:
        set: "carbon"
        width: "1em"
        height: "1em"
        inline: true
        mode: "svg"
        style: "color: #6f6f6f"
---

:::{.callout-note icon=false}
The Civil Service benchmark is calculated for each measure as the
median score of the participating organisations - half of organisations will
score above this figure and half of organisations will score below this figure.
The figures for [all respondents](all_respondents/index.qmd) are also available.
:::
<!--close 18 -->

## Headline results

:::{.print-break-after}

The People Survey's headline results focus on measuring employee engagement
and it's key drivers. The employee engagement index is based on five questions
that measure civil servants' levels of advocacy for, attachment to and
motivation towards the civil service organisation they currently work for.

In 2024 the Civil Service benchmark for employee engagement 64%, unchanged
from 2023.

:::{.grid .theme-card-wide}
:::{.g-col-4}
[Engagement index]{.theme-header}

<div>
<span class="data-value">64%</span> <span class="change-value no-change">±0</span>
<p>[Skip to question results](#employee-engagement){.read-more}</p>
</div>

:::
<!--close 39-->

:::{.g-col-8 .text-end}
```{=html}
<iframe width="400" height="200", src="test.svg"></iframe>
```
:::
<!--close 50-->

:::
<!--close 38-->

:::{.callout-note title="Engagement index calculation" collapse="true"}
The engagement index is calculated as a weighted average of the five questions
that make up the index. An index score of 0% represents all respondents
answering strongly disagree to all five questions while a index score of 100%
represents all respondents answering strongly agree to all five questions.
:::
<!--close 58-->

:::
<!--close 28-->

### Drivers of engagement

The People Survey measures nine 'themes' that are drivers of employee
engagement. The summary cards below show the overall score for each theme,
the difference from last year and the long-term trend from 2009 to 2024.

All themes have an influence on levels of employee engagement, but some have
stronger associations with levels of employee engagement than others. Next to
the name of each theme is a small signal-bar icon indicating the strength of
association between that theme and the engagement index.

:::{.callout-tip title="Guide to symbols" collapse="true"}

| Icon | Description |
| -: | :------------------------- |
| [{{< iconify skill-level-advanced title="Strong association icon" label="Strong association icon" style="color:#1192e8;" >}}]{.driver-strength} | **Strong association:** if scores in these themes are low then prioritise action in these areas to improve employee engagement. |
| [{{< iconify skill-level-intermediate title="Moderate association icon" label="Moderate association icon" style="color:#1192e8;" >}}]{.driver-strength} | **Moderate association:** while not as direct as the first three drivers these themes still have a notable impact, they're often important for maintaining high levels of employee engagement. |
| [{{< iconify skill-level-basic title="Weak association icon" label="Weak association icon" style="color:#1192e8;" >}}]{.driver-strength} | **Weak association:** these themes have background influence on levels of employee engagement, keep a watch to make sure they don't drop.
: {.sm .small}

:::

:::{.grid .card-row}

:::{.g-col-12 .g-col-sm-4 .theme-card}
[My work]{.theme-header}
[{{< iconify skill-level-advanced title="Strong association icon" label="Strong association icon" style="color:#1192e8;" >}}]{.driver-strength}

<span class="data-value">77%</span> <span class="change-value decrease">-1</span>

<div>

{{< placeholder 200 100 format=svg >}}

[Skip to question results](#my-work){.read-more}

</div>

:::
<!--close 95-->

:::{.g-col-12 .g-col-sm-4 .theme-card}
[Organisational objectives and purpose]{.theme-header}
[{{< iconify skill-level-intermediate title="Moderate association icon" label="Moderate association icon" style="color:#1192e8;" >}}]{.driver-strength}

<span class="data-value">83%</span> <span class="change-value decrease">-1</span>

<div>

{{< placeholder 200 100 format=svg >}}

[Skip to question results](#organisational-objectives-and-purpose){.read-more}

</div>

:::
<!--close 112-->

:::{.g-col-12 .g-col-sm-4 .theme-card}

[My manager]{.theme-header}
[{{< iconify skill-level-advanced title="Strong association icon" label="Strong association icon" style="color:#1192e8;" >}}]{.driver-strength}

<span class="data-value">78%</span> <span class="change-value increase">+1</span>

<div>

{{< placeholder 200 100 format=svg >}}

[Skip to question results](#my-manager){.read-more}

</div>

:::
<!--close 129-->

:::{.g-col-12 .g-col-sm-4 .theme-card}
[My team]{.theme-header}
[{{< iconify skill-level-intermediate title="Moderate association icon" label="Moderate association icon" style="color:#1192e8;" >}}]{.driver-strength}

<span class="data-value">84%</span> <span class="change-value no-change">±0</span>

<div>

{{< placeholder 200 100 format=svg >}}

[Skip to question results](#my-team){.read-more}

</div>

:::
<!--close 147-->

:::{.g-col-12 .g-col-sm-4 .theme-card}
[Learning and development]{.theme-header}
[{{< iconify skill-level-intermediate title="Moderate association icon" label="Moderate association icon" style="color:#1192e8;" >}}]{.driver-strength}

<span class="data-value">56%</span> <span class="change-value no-change">±0</span>

<div>

{{< placeholder 200 100 format=svg >}}

[Skip to question results](#learning-and-development){.read-more}

</div>

:::
<!--close 164-->

:::{.g-col-12 .g-col-sm-4 .theme-card}
[Inclusion and fair treatment]{.theme-header}
[{{< iconify skill-level-basic title="Weak association icon" label="Weak association icon" style="color:#1192e8;" >}}]{.driver-strength}

<span class="data-value">81%</span> <span class="change-value no-change">±0</span>

<div>

{{< placeholder 200 100 format=svg >}}

[Skip to question results](#inclusion-and-fair-treatment){.read-more}

</div>

:::
<!--close 181-->

:::{.g-col-12 .g-col-sm-4 .theme-card}

[Resources and workload]{.theme-header}
[{{< iconify skill-level-basic title="Weak association icon" label="Weak association icon" style="color:#1192e8;" >}}]{.driver-strength}

<span class="data-value">76%</span> <span class="change-value no-change">+1</span>

<div>

{{< placeholder 200 100 format=svg >}}

[Skip to question results](#resources-and-workload){.read-more}

</div>

:::
<!--close 198-->

:::{.g-col-12 .g-col-sm-4 .theme-card}
[Pay and benefits]{.theme-header}
[{{< iconify skill-level-basic title="Weak association icon" label="Weak association icon" style="color:#1192e8;" >}}]{.driver-strength}

<span class="data-value">34%</span> <span class="change-value no-change">+2</span>

<div>

{{< placeholder 200 100 format=svg >}}

[Skip to question results](#pay-and-benefits){.read-more}

</div>

:::
<!--close 216-->

:::{.g-col-12 .g-col-sm-4 .theme-card}
[Leadership and managing change]{.theme-header}
[{{< iconify skill-level-advanced title="Strong association icon" label="Strong association icon" style="color:#1192e8;" >}}]{.driver-strength}

<span class="data-value">52%</span> <span class="change-value no-change">±0</span>

<div>

{{< placeholder 200 100 format=svg >}}

[Skip to question results](#leadership-and-managing-change){.read-more}

</div>

:::
<!--close 233-->

:::
<!--close 93-->

:::{.callout-note title="Theme score calculation" collapse="true"}
The score for a given theme is the average percent positive response (a
'strongly agree' or 'agree' response) across its constituent questions.
:::
<!--close 253-->

:::{.callout-note title="Driver calculation" collapse="true"}
The strength of association is derived from a combination of factor analysis
and regression modelling of the published results.
:::
<!--close 259-->

### Discrimination, bullying and harassment

:::{.grid}
:::{.g-col-12 .g-col-sm-4 .theme-card}
[Experienced discrimination]{.theme-header}

<span class="data-value">7%</span> <span class="change-value no-change">±0</span>

<div>

{{< placeholder 200 100 format=svg >}}

[Skip to question results](#discrimination-at-work){.read-more}

</div>

:::
<!--close 268-->

:::{.g-col-12 .g-col-sm-4 .theme-card}
[Experienced bullying]{.theme-header}

<span class="data-value">8%</span> <span class="change-value no-change">±0</span>

<div>

{{< placeholder 200 100 format=svg >}}

[Skip to question results](#bullying-and-harassment){.read-more}

</div>

:::
<!--close 284-->

:::
<!--close 267-->

...

## Question results: overview

The engagement index and theme scores are headline scores that provide a quick
overview of the People Survey results, these scores are derived from the
results of individual questions. The rest of this report provides an overview
of the results of each question in the survey, grouped by survey section and
theme.

Overall we divide the survey results into four broad sections:

* [Employee engagement and core themes](#question-results-employee-engagement-and-core-themes)
* [Future intentions](#question-results-future-intentions)
* [Discrimination, bullying and harassment](#discrimination-bullying-and-harassment)
* [Wellbeing](#question-results-wellbeing)
* [Other questions](#question-results-other-questions)

Unless otherwise stated results are the percentage responding 'strongly agree'
or 'agree' to the statement/question.

### Biggest increases

The five questions with the biggest increases in score between 2023 and 2024
were:

:::{.column-page-inset-right .results-table}

| Question | 2023 | 2024 | | Difference |
|:----------------| ----:| ----:|:-| ----:|
| Over the last 12 months money worries have affected my ability to do my job (% seldom or never) | 55.7% | 61.6% | <span class="micro-chart"><span class="micro-bar" data-value="62"></span></span> | +5.9 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| I understand the Civil Service Code and what it means for my conduct | 88.2% | 92.1% | <span class="micro-chart"><span class="micro-bar" data-value="92"></span></span> | +3.9 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| I feel that my pay adequately reflects my performance | 31.7% | 35.5% | <span class="micro-chart"><span class="micro-bar" data-value="36"></span></span> | +3.8 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Senior managers in [my organisation] are sufficiently visible | 70.6% | 73.0% | <span class="micro-chart"><span class="micro-bar" data-value="73"></span></span> | +2.4 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| How often do you collaborate with civil servants in other government departments and agencies to achieve common goals? (% always, often, some of the time) | 37.3% | 39.1% | <span class="micro-chart"><span class="micro-bar" data-value="39"></span></span> | +1.8 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |

:::
<!--close 329-->

### Biggest decreases

The five questions with the biggest decreases in score between 2023 and 2024
were:

:::{.column-page-inset-right .results-table}

| Question | 2023 | 2024 | | Difference |
|:----------------| ----:| ----:|:-| ----:|
| I have a choice in deciding where I do my work (usual workplace or base, another workplace, home) | 83.2% | 73.3% | <span class="micro-chart"><span class="micro-bar" data-value="73"></span></span> | -9.9 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| Efficiency is pursued as a priority in [my organisation] | 54.8% | 52.3% | <span class="micro-chart"><span class="micro-bar" data-value="39"></span></span> | -2.5 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| I think that [my organisation] respects individual differences (for example, cultures, working styles, backgrounds, ideas, etc.) | 80.5% | 79.1% | <span class="micro-chart"><span class="micro-bar" data-value="79"></span></span> | -1.4 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| I feel involved in the decisions that affect my work | 61.4% | 60.0% | <span class="micro-chart"><span class="micro-bar" data-value="60"></span></span> | -1.4 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| There are opportunities for me to develop my career in [my organisation] | 53.3% | 52.0% | <span class="micro-chart"><span class="micro-bar" data-value="52"></span></span> | -1.3 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |

:::
<!--close 347-->

## Question results: Employee engagement and core themes

The main focus of the People Survey is measuring levels of employee engagement
and its drivers. This section highlights the key results for each of the driver
themes and the engagement index.

### My work

[{{< iconify skill-level-advanced title="Strong association icon" label="Strong association icon" style="color:#1192e8;" >}}]{.driver-strength}
This theme has a strong association with higher levels of employee engagement.

:::{.column-page-inset-right .results-table}

| Question        | 2023| 2024| | Difference|
|:----------------| ----:| ----:|:-| ----:|
| I am interested in my work | 90.2% | 90.0% | <span class="micro-chart"><span class="micro-bar" data-value="90"></span> | -0.2 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}}|
| I am sufficiently challenged by my work | 82.6% | 82.1% | <span class="micro-chart"><span class="micro-bar" data-value="82"></span> | -0.5 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}}|
| My work gives me a sense of personal accomplishment | 77.6% | 77.5% | <span class="micro-chart"><span class="micro-bar" data-value="78"></span> | -0.1 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}}|
| I feel involved in the decisions that affect my work | 61.4% | 60.0% | <span class="micro-chart"><span class="micro-bar" data-value="60"></span> | -1.4 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}}|
| I have a choice in deciding how I do my work | 80.8% | 80.9% | <span class="micro-chart"><span class="micro-bar" data-value="81"></span> | +0.1 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}}|

:::
<!--close 371-->

### Organisational objectives and purpose

[{{< iconify skill-level-intermediate title="Moderate association icon" label="Moderate association icon" style="color:#1192e8;" >}}]{.driver-strength}
This theme has a medium association with higher levels of employee engagement.

:::{.column-page-inset-right .results-table}

| Question        | 2023| 2024| | Difference|
|:----------------| ----:| ----:|:-| ----:|
| I have a clear understanding of [my organisation]'s objectives | 82.9% | 81.9% | <span class="micro-chart"><span class="micro-bar" data-value="82"></span> | -1.0 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}}|
| I understand how my work contributes to [my organisation]'s objectives | 85.0% | 84.9% | <span class="micro-chart"><span class="micro-bar" data-value="85"></span> | -0.1 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}}|

:::
<!--close 389-->

### My manager

[{{< iconify skill-level-advanced title="Strong association icon" label="Strong association icon" style="color:#1192e8;" >}}]{.driver-strength}
This theme has a strong association with higher levels of employee engagement.

:::{.column-page-inset-right .results-table}

| Question        | 2023| 2024| | Difference|
|:----------------| ----:| ----:|:-| ----:|
| My manager motivates me to be more effective in my job | 76.3% | 76.0% | <span class="micro-chart"><span class="micro-bar" data-value="76"></span> | -0.3 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}}|
| My manager is considerate of my life outside work | 89.8% | 90.4% | <span class="micro-chart"><span class="micro-bar" data-value="90"></span> | +0.6 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}}|
| My manager is open to my ideas | 86.6% | 86.1% | <span class="micro-chart"><span class="micro-bar" data-value="86"></span> | -0.5 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}}|
| My manager helps me to understand how I contribute to [my organisation]'s objectives | 72.0% | 71.4% | <span class="micro-chart"><span class="micro-bar" data-value="71"></span> | -0.6 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}}|
| Overall, I have confidence in the decisions made by my manager | 80.9% | 81.0% | <span class="micro-chart"><span class="micro-bar" data-value="81"></span> | +0.1 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}}|
| My manager recognises when I have done my job well | 83.4% | 83.7% | <span class="micro-chart"><span class="micro-bar" data-value="84"></span> | +0.3 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}}|
| I receive regular feedback on my performance | 72.5% | 73.6% | <span class="micro-chart"><span class="micro-bar" data-value="74"></span> | +1.1 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}}|
| The feedback I receive helps me to improve my performance | 68.7% | 68.6% | <span class="micro-chart"><span class="micro-bar" data-value="69"></span> | -0.1 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}}|
| I think that my performance is evaluated fairly | 72.9% | 73.1% | <span class="micro-chart"><span class="micro-bar" data-value="73"></span> | +0.2 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}}|
| Have you heard of the Civil Service line management standards? (% yes) | — | 49.0% | <span class="micro-chart"><span class="micro-bar" data-value="49"></span> | — |

:::
<!--close 404-->

:::{.callout-tip title="Questionnaire changes" collapse="true"}
The question *'Have you heard of the Civil Service line management standards'*
is new for 2024 and does not contribute towards the calculation of the 'My
manager' theme score.
:::
<!--close 421-->

### My team

[{{< iconify skill-level-intermediate title="Moderate association icon" label="Moderate association icon" style="color:#1192e8;" >}}]{.driver-strength}
This theme has a medium association with higher levels of employee engagement.

:::{.column-page-inset-right .results-table}

| Question     | 2023 | 2024 |  | Difference |
| :---------------- | ----: | ----: | :- | ----: |
| The people in my team can be relied upon to help when things get difficult in my job | 87.5% | 88.0% | <span class="micro-chart"><span class="micro-bar" data-value="88"></span> | +0.5 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| The people in my team work together to find ways to improve the service we provide | 84.5% | 85.4% | <span class="micro-chart"><span class="micro-bar" data-value="85"></span> | +0.9 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| The people in my team are encouraged to come up with new and better ways of doing things | 78.4% | 78.6% | <span class="micro-chart"><span class="micro-bar" data-value="79"></span> | +0.2 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |

:::

### Learning and development

[{{< iconify skill-level-intermediate title="Moderate association icon" label="Moderate association icon" style="color:#1192e8;" >}}]{.driver-strength}
This theme has a moderate association with higher levels of employee engagement.

:::{.column-page-inset-right .results-table}

| Question     | 2023 | 2024 |  | Difference |
| :---------------- | ----: | ----: | :- | ----: |
| I am able to access the right learning and development opportunities when I need to | 66.9% | 67.5% | <span class="micro-chart"><span class="micro-bar" data-value="68"></span> | +0.6 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Learning and development activities I have completed in the past 12 months have helped to improve my performance | 52.3% | 53.5% | <span class="micro-chart"><span class="micro-bar" data-value="54"></span> | +1.2 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| There are opportunities for me to develop my career in [my organisation] | 53.3% | 52.0% | <span class="micro-chart"><span class="micro-bar" data-value="52"></span> | -1.3 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| Learning and development activities I have completed while working for [my organisation] are helping me to develop my career | 50.6% | 51.2% | <span class="micro-chart"><span class="micro-bar" data-value="51"></span> | +0.6 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |

:::

### Inclusion and fair treatment

[{{< iconify skill-level-basic title="Weak association icon" label="Weak association icon" style="color:#1192e8;" >}}]{.driver-strength}
This theme has a weak association with higher levels of employee engagement.

:::{.column-page-inset-right .results-table}

| Question     | 2023 | 2024 |  | Difference |
| :---------------- | ----: | ----: | :- | ----: |
| I am treated fairly at work | 84.1% | 83.5% | <span class="micro-chart"><span class="micro-bar" data-value="84"></span> | -0.6 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| I am treated with respect by the people I work with | 88.2% | 88.0% | <span class="micro-chart"><span class="micro-bar" data-value="88"></span> | -0.2 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| I feel valued for the work I do | 72.1% | 71.6% | <span class="micro-chart"><span class="micro-bar" data-value="72"></span> | -0.5 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| I think that [my organisation] respects individual differences (for example, cultures, working styles, backgrounds, ideas, etc.) | 80.5% | 79.1% | <span class="micro-chart"><span class="micro-bar" data-value="79"></span> | -1.4 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |

:::

### Resources and workload

[{{< iconify skill-level-basic title="Weak association icon" label="Weak association icon" style="color:#1192e8;" >}}]{.driver-strength}
This theme has a weak association with higher levels of employee engagement.

:::{.column-page-inset-right .results-table}

| Question     | 2023 | 2024 |  | Difference |
| :---------------- | ----: | ----: | :- | ----: |
| I get the information I need to do my job well | 70.9% | 70.6% | <span class="micro-chart"><span class="micro-bar" data-value="71"></span> | -0.3 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| I have clear work objectives | 77.3% | 77.2% | <span class="micro-chart"><span class="micro-bar" data-value="77"></span> | -0.1 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| I have the skills I need to do my job effectively | 89.3% | 90.2% | <span class="micro-chart"><span class="micro-bar" data-value="90"></span> | +0.9 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| I have the tools I need to do my job effectively | 73.5% | 75.2% | <span class="micro-chart"><span class="micro-bar" data-value="75"></span> | +1.7 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| I have an acceptable workload | 64.1% | 65.7% | <span class="micro-chart"><span class="micro-bar" data-value="66"></span> | +1.6 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| I achieve a good balance between my work life and my private life | 74.4% | 75.8% | <span class="micro-chart"><span class="micro-bar" data-value="76"></span> | +1.4 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |

:::

### Pay and benefits

[{{< iconify skill-level-basic title="Weak association icon" label="Weak association icon" style="color:#1192e8;" >}}]{.driver-strength}
This theme has a weak association with higher levels of employee engagement.

:::{.column-page-inset-right .results-table}

| Question     | 2023 | 2024 |  | Difference |
| :---------------- | ----: | ----: | :- | ----: |
| I feel that my pay adequately reflects my performance | 31.7% | 35.5% | <span class="micro-chart"><span class="micro-bar" data-value="36"></span> | +3.8 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| I am satisfied with the total benefits package (e.g. base pay, benefits and pension) | 38.8% | 39.8% | <span class="micro-chart"><span class="micro-bar" data-value="40"></span> | +1.0 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Compared to people doing a similar job in other organisations I feel my pay is reasonable | 25.7% | 27.0% | <span class="micro-chart"><span class="micro-bar" data-value="27"></span> | +1.3 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| I am fully aware of the benefits available in [my organisation], in addition to pay | 70.3% | 70.6% | <span class="micro-chart"><span class="micro-bar" data-value="71"></span> | +0.3 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Over the last 12 months money worries have affected my ability to do my job (% seldom or never) | 55.7% | 61.6% | <span class="micro-chart"><span class="micro-bar" data-value="62"></span> | +5.9 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |

:::

:::{.callout-tip title="Questionnaire changes" collapse="true"}
The questions *'I am fully aware of the benefits available in [my organisation],
in addition to pay'* and *'Over the last 12 months money worries have affected
my ability to do my job'* were first introduced in 2023 and doe not contribute
towards the calculation of the 'Pay and benefits' theme score.
:::

### Leadership and managing change

[{{< iconify skill-level-advanced title="Strong association icon" label="Strong association icon" style="color:#1192e8;" >}}]{.driver-strength}
This theme has a strong association with higher levels of employee engagement.

:::{.column-page-inset-right .results-table}

| Question     | 2023 | 2024 |  | Difference |
| :---------------- | ----: | ----: | :- | ----: |
| Senior managers in [my organisation] are sufficiently visible | 70.6% | 73.0% | <span class="micro-chart"><span class="micro-bar" data-value="73"></span> | +2.4 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| I believe the actions of senior managers are consistent with [my organisation]'s values | 64.8% | 65.5% | <span class="micro-chart"><span class="micro-bar" data-value="66"></span> | +0.7 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| I believe that [my organisation]'s senior leaders have a clear vision for the future of [my organisation] | 53.7% | 53.8% | <span class="micro-chart"><span class="micro-bar" data-value="54"></span> | +0.1 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Overall, I have confidence in the decisions made by [my organisation]'s senior managers | 56.0% | 56.2% | <span class="micro-chart"><span class="micro-bar" data-value="56"></span> | +0.2 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| I feel that change is managed well in [my organisation] | 34.2% | 33.1% | <span class="micro-chart"><span class="micro-bar" data-value="33"></span> | -1.1 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| When changes are made in [my organisation] they are usually for the better | 34.1% | 34.6% | <span class="micro-chart"><span class="micro-bar" data-value="35"></span> | +0.5 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| [My organisation] keeps me informed about matters that affect me | 64.2% | 64.3% | <span class="micro-chart"><span class="micro-bar" data-value="64"></span> | +0.1 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| I have the opportunity to contribute my views before decisions are made that affect me | 40.3% | 39.1% | <span class="micro-chart"><span class="micro-bar" data-value="39"></span> | -1.2 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| I think it is safe to challenge the way things are done in [my organisation] | 51.4% | 51.0% | <span class="micro-chart"><span class="micro-bar" data-value="51"></span> | -0.4 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |

:::

### Employee engagement

:::{.column-page-inset-right .results-table}

| Question     | 2023 | 2024 |  | Difference |
| :---------------- | ----: | ----: | :- | ----: |
| I am proud when I tell others I am part of [my organisation] | 65.2% | 65.9% | <span class="micro-chart"><span class="micro-bar" data-value="66"></span> | +0.7 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| I would recommend [my organisation] as a great place to work | 61.5% | 63.3% | <span class="micro-chart"><span class="micro-bar" data-value="63"></span> | +1.8 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| I feel a strong personal attachment to [my organisation] | 50.0% | 50.8% | <span class="micro-chart"><span class="micro-bar" data-value="51"></span> | +0.8 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| [My organisation] inspires me to do the best in my job | 53.9% | 55.0% | <span class="micro-chart"><span class="micro-bar" data-value="55"></span> | +1.1 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| [My organisation] motivates me to help it achieve its objectives | 51.7% | 52.8% | <span class="micro-chart"><span class="micro-bar" data-value="53"></span> | +1.1 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |

:::

### Taking action

:::{.column-page-inset-right .results-table}

| Question     | 2023 | 2024 |  | Difference |
| :---------------- | ----: | ----: | :- | ----: |
| I believe that senior managers in [my organisation] will take action on the results from this survey | 51.2% | 51.8% | <span class="micro-chart"><span class="micro-bar" data-value="52"></span> | +0.6 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Where I work, I think effective action has been taken on the results of the last survey | 38.1% | 37.6% | <span class="micro-chart"><span class="micro-bar" data-value="38"></span> | -0.5 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |

:::

### Future intentions

:::{.column-page-inset-right .results-table}

| Response     | 2023 | 2024 |  | Difference |
| :---------------- | ----: | ----: | :- | ----: |
| I want to leave [my organisation] as soon as possible | 7.2% | 6.4% | <span class="micro-chart"><span class="micro-bar" data-value="6"></span> | -0.8  {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| I want to leave [my organisation] within the next 12 months | 14.8% | 13.6% | <span class="micro-chart"><span class="micro-bar" data-value="14"></span> | -1.2 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| I want to stay working for [my organisation] for at least the next year | 35.9% | 35.4% | <span class="micro-chart"><span class="micro-bar" data-value="35"></span> | -0.5 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| I want to stay working for [my organisation] for at least the next three years | 42.5% | 44.5% | <span class="micro-chart"><span class="micro-bar" data-value="45"></span> | +2.0 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
: Which of the following statements most reflects your current thoughts about working for [your organisation]?

| Response (multiple-choice) | 2023 | 2024 | | Difference |
| :---------------- | ----: | ----: | :- | ----: |
| End of my current contract or loan | 3.8% | 2.7% | <span class="micro-chart"><span class="micro-bar" data-value="3"></span> | -1.1 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| A promotion or career progression within the Civil Service | 35.6% | 37.5% | <span class="micro-chart"><span class="micro-bar" data-value="38"></span> | +1.9 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| A promotion or career progression outside of the Civil Service | 21.3% | 22.3% | <span class="micro-chart"><span class="micro-bar" data-value="22"></span> | +1.0 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| For a better pay and benefit package | 50.0% | 44.4% | <span class="micro-chart"><span class="micro-bar" data-value="44"></span> | -5.6 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| For more interesting work | 29.3% | 30.8% | <span class="micro-chart"><span class="micro-bar" data-value="31"></span> | +1.5 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Due to unmanageable workload | 18.3% | 16.2% | <span class="micro-chart"><span class="micro-bar" data-value="16"></span> | -2.1 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| For a better work-life balance | 19.9% | 20.5% | <span class="micro-chart"><span class="micro-bar" data-value="21"></span> | +0.6 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Lack of inclusion and fair treatment | 13.9% | 16.1% | <span class="micro-chart"><span class="micro-bar" data-value="16"></span> | +2.2 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Don’t like organisational culture | 25.5% | 26.8% | <span class="micro-chart"><span class="micro-bar" data-value="27"></span> | +1.3 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Due to poor line management | 16.7% | 17.6% | <span class="micro-chart"><span class="micro-bar" data-value="18"></span> | +0.9 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Due to poor work relationships | 6.9% | 7.8% | <span class="micro-chart"><span class="micro-bar" data-value="8"></span> | +0.9 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Due to poor leadership | 28.3% | 28.9% | <span class="micro-chart"><span class="micro-bar" data-value="29"></span> | +0.6 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Personal circumstances (for example, caring responsibilities, ill health) | 6.6% | 7.5% | <span class="micro-chart"><span class="micro-bar" data-value="8"></span> | +0.9 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Retiring | 5.7% | 6.6% | <span class="micro-chart"><span class="micro-bar" data-value="7"></span> | +0.9 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Just want a change | 16.9% | 18.0% | <span class="micro-chart"><span class="micro-bar" data-value="18"></span> | +1.1 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Other | 8.2% | 8.5% | <span class="micro-chart"><span class="micro-bar" data-value="9"></span> | +0.3 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
: Why do you want to leave [your organisation] immediately or within the next 12 months? *(asked only to those who said they wanted to leave their organisation as soon as possible or in the next 12 months)*

:::

:::{.callout-warning title="Caution when interpreting differences between years" collapse="true"}
The benchmark figures are calculated as the median score across all
participating organisations for each separate measure. For the questions on
future intentions each question response is treated as a separate measure, as a
result the net sum of differences may not be zero due to the underlying
variation in organisation scores.

Depending on the nature of your interest in this question, the results for
[all respondents](all_respondents/index.qmd) may be more relevant than the
Civil Service benchmark.
:::

## Question results: Discrimination, bullying and harassment

The People Survey asks civil servants if they have experienced either
discrimination, or bullying or harassment in the past 12 months. For those
that say they have the survey goes on to ask some follow-up questions to
better understand the nature of their experiences.

### Discrimination at work

> Discrimination is when an employer treats an employee less favourably than
> someone else, or  when a working condition, policy, procedure or rule
> disadvantages one group of people more than another.
>
> *Civil Service People Survey questionnaire (2013)*

:::{.column-page-inset-right .results-table}

| Response | 2023 | 2024 | | Difference |
| :---------------- | ----: | ----: | :- | ----: |
| Yes | 7.3% | 7.3% | <span class="micro-chart"><span class="micro-bar" data-value="7"></span> | ±0.0 {{< iconify not-available title="Score unchanged icon" label="Score unchanged icon" >}} |
| No | 86.5% | 86.4% | <span class="micro-chart"><span class="micro-bar" data-value="86"></span> | -0.1 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| Prefer not to say | 6.3% | 6.5% | <span class="micro-chart"><span class="micro-bar" data-value="7"></span> | +0.2 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
: Have you been discriminated against at work in the last 12 months?

| Response (multiple-choice) | 2023 | 2024 | | Difference |
| :---------------- | ----: | ----: | :- | ----: |
| Age | 16.2% | 16.4% | <span class="micro-chart"><span class="micro-bar" data-value="16"></span> | +0.2 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Caring responsibilities | 10.0% | 10.7% | <span class="micro-chart"><span class="micro-bar" data-value="11"></span> | +0.7 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Disability | 14.7% | 18.9% | <span class="micro-chart"><span class="micro-bar" data-value="19"></span> | +4.2 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Ethnic background | 8.4% | 9.2% | <span class="micro-chart"><span class="micro-bar" data-value="9"></span> | +0.8 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Gender | 15.3% | 15.6% | <span class="micro-chart"><span class="micro-bar" data-value="16"></span> | +0.3 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Gender reassignment or perceived gender | 0.0% | 0.0% | <span class="micro-chart"><span class="micro-bar" data-value="0"></span> | ±0.0 {{< iconify not-available title="Score unchanged icon" label="Score unchanged icon" >}} |
| Grade or responsibility level | 23.2% | 25.4% | <span class="micro-chart"><span class="micro-bar" data-value="25"></span> | +2.2 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Main spoken, written language or language ability | 3.7% | 3.8% | <span class="micro-chart"><span class="micro-bar" data-value="4"></span> | +0.1 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Marital status or civil partnership | 0.2% | 0.0% | <span class="micro-chart"><span class="micro-bar" data-value="0"></span> | -0.2 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| Mental health | 12.7% | 12.8% | <span class="micro-chart"><span class="micro-bar" data-value="13"></span> | +0.1 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Pay | 7.6% | 7.2% | <span class="micro-chart"><span class="micro-bar" data-value="7"></span> | -0.4 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| Pregnancy, maternity or paternity | 1.4% | 2.1% | <span class="micro-chart"><span class="micro-bar" data-value="2"></span> | +0.7 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Religion or belief | 2.1% | 2.0% | <span class="micro-chart"><span class="micro-bar" data-value="2"></span> | -0.1 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| Sex | 3.3% | 3.6% | <span class="micro-chart"><span class="micro-bar" data-value="4"></span> | +0.3 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Sexual orientation | 1.8% | 1.8% | <span class="micro-chart"><span class="micro-bar" data-value="2"></span> | ±0.0 {{< iconify not-available title="Score unchanged icon" label="Score unchanged icon" >}} |
| Social or educational background | 4.1% | 5.1% | <span class="micro-chart"><span class="micro-bar" data-value="5"></span> | +1.0 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Working location | 14.7% | 14.8% | <span class="micro-chart"><span class="micro-bar" data-value="15"></span> | +0.1 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Working pattern | 15.3% | 15.0% | <span class="micro-chart"><span class="micro-bar" data-value="15"></span> | -0.3 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| Any other grounds | 10.8% | 10.3% | <span class="micro-chart"><span class="micro-bar" data-value="10"></span> | -0.5 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| Prefer not to say | 10.6% | 11.1% | <span class="micro-chart"><span class="micro-bar" data-value="11"></span> | +0.5 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
: On which of the following grounds were you discriminated against? *(asked only to those whose who said they experienced discrimination at work in the past 12 months)*

:::

### Bullying and harassment

> Bullying is offensive, intimidating, malicious or insulting behaviour, an
> abuse or misuse of power through means intended to undermine, humiliate,
> denigrate or injure the recipient.
>
> Harassment is unwanted actions or comments that are demeaning and
> unacceptable to the recipient. It may be related to any personal
> characteristic of the individual, and may be persistent or an isolated
> incident.
>
> *Civil Service People Survey questionnaire (2013)*

:::{.column-page-inset-right .results-table}

| Response | 2023 | 2024 | | Difference |
| :---------------- | ----: | ----: | :- | ----: |
| Yes | 7.9% | 7.6% | <span class="micro-chart"><span class="micro-bar" data-value="8"></span> | -0.3 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| No | 86.8% | 86.9% | <span class="micro-chart"><span class="micro-bar" data-value="87"></span> | +0.1 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Prefer not to say | 5.4% | 5.6% | <span class="micro-chart"><span class="micro-bar" data-value="6"></span> | +0.2 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
: Have you been bullied or harassed at work, in the past 12 months?

:::

#### Nature of bullying and harassment

:::{.column-page-inset-right .results-table}

| Response (multiple-choice) | 2023 | 2024 | | Difference |
| :---------------- | ----: | ----: | :- | ----: |
| Comments about my personal appearance or accent | 8.0% | 7.3% | <span class="micro-chart"><span class="micro-bar" data-value="7"></span> | -0.7 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| Sexual harassment (for example, sexual comments or jokes, unwelcome sexual advances, touching or assault) | 3.8% | 2.7% | <span class="micro-chart"><span class="micro-bar" data-value="3"></span> | -1.1 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| Spreading gossip or making false accusations about me | 22.3% | 25.0% | <span class="micro-chart"><span class="micro-bar" data-value="25"></span> | +2.7 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Intimidation, or verbal or written aggression (for example, shouting, making threats, sending aggressive emails) | 35.8% | 35.9% | <span class="micro-chart"><span class="micro-bar" data-value="36"></span> | +0.1 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Physical assault (for example, object thrown at me, pushed, hit) | 0.0% | 0.0% | <span class="micro-chart"><span class="micro-bar" data-value="0"></span> | ±0.0 {{< iconify not-available title="Score unchanged icon" label="Score unchanged icon" >}} |
| Humiliated in front of team or others | 36.4% | 36.5% | <span class="micro-chart"><span class="micro-bar" data-value="37"></span> | +0.1 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Negative micromanagement (for example, excessive control, made to feel incompetent) | 52.9% | 51.6% | <span class="micro-chart"><span class="micro-bar" data-value="52"></span> | -1.3 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| Removal of job responsibilities, unconstructive criticism, or changing expectations | 30.9% | 30.9% | <span class="micro-chart"><span class="micro-bar" data-value="31"></span> | ±0.0 {{< iconify not-available title="Score unchanged icon" label="Score unchanged icon" >}} |
| Treated less favourably to others | 37.8% | 39.1% | <span class="micro-chart"><span class="micro-bar" data-value="39"></span> | +1.3 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Ignored, excluded, marginalised | 35.3% | 37.3% | <span class="micro-chart"><span class="micro-bar" data-value="37"></span> | +2.0 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Undermining or taking credit for my work | 30.1% | 27.4% | <span class="micro-chart"><span class="micro-bar" data-value="27"></span> | -2.7 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| Denied time off for personal ill health | 1.6% | 1.7% | <span class="micro-chart"><span class="micro-bar" data-value="2"></span> | +0.1 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Denied time off for family or caring responsibilities | 2.3% | 2.5% | <span class="micro-chart"><span class="micro-bar" data-value="3"></span> | +0.2 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Disclosure of personal or sensitive information to colleagues without my consent | 7.9% | 8.7% | <span class="micro-chart"><span class="micro-bar" data-value="9"></span> | +0.8 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Unhelpful comments about my mental health or being off sick | 10.0% | 11.1% | <span class="micro-chart"><span class="micro-bar" data-value="11"></span> | +1.1 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Something else not listed here | 7.3% | 7.7% | <span class="micro-chart"><span class="micro-bar" data-value="8"></span> | +0.4 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Prefer not to say | 2.9% | 3.5% | <span class="micro-chart"><span class="micro-bar" data-value="4"></span> | +0.6 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
: How would you describe the nature of the bullying and or harassment you experienced? *(asked only to those whose who said they experienced bullying or harassment at work in the past 12 months)*

| Response (multiple-choice) | 2023 | 2024 | | Difference |
| :---------------- | ----: | ----: | :- | ----: |
| A colleague in my area, directorate or division | 33.7% | 36.0% | <span class="micro-chart"><span class="micro-bar" data-value="36"></span> | +2.3 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| A colleague in a different area, directorate, division of my organisation | 11.2% | 11.1% | <span class="micro-chart"><span class="micro-bar" data-value="11"></span> | -0.1 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| My manager | 31.8% | 30.8% | <span class="micro-chart"><span class="micro-bar" data-value="31"></span> | -1.0 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| Another senior member of staff in my organisation | 23.4% | 24.2% | <span class="micro-chart"><span class="micro-bar" data-value="24"></span> | +0.8 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Someone I manage | 4.8% | 5.1% | <span class="micro-chart"><span class="micro-bar" data-value="5"></span> | +0.3 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
| Someone working in a different Civil Service organisation | 3.0% | 1.9% | <span class="micro-chart"><span class="micro-bar" data-value="2"></span> | -1.1 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| Someone working for a non-Civil Service organisation | 0.5% | 0.0% | <span class="micro-chart"><span class="micro-bar" data-value="0"></span> | -0.5 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| A contractor | 0.8% | 0.7% | <span class="micro-chart"><span class="micro-bar" data-value="1"></span> | -0.1 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| A service user (for example, customer, claimant, offender) | 0.7% | 0.3% | <span class="micro-chart"><span class="micro-bar" data-value="0"></span> | -0.4 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| A member of the public | 0.0% | 0.0% | <span class="micro-chart"><span class="micro-bar" data-value="0"></span> | ±0.0 {{< iconify not-available title="Score unchanged icon" label="Score unchanged icon" >}} |
| Someone else not listed here | 4.1% | 3.9% | <span class="micro-chart"><span class="micro-bar" data-value="4"></span> | -0.2 {{< iconify triangle-down-solid title="Score decreased icon" label="Score decreased icon" style="color:#da1e28" >}} |
| Prefer not to say | 8.6% | 9.2% | <span class="micro-chart"><span class="micro-bar" data-value="9"></span> | +0.6 {{< iconify triangle-solid title="Score increased icon" label="Score increased icon" style="color:#007d79" >}} |
: Who bullied or harassed you? *(asked only to those whose who said they experienced bullying or harassment at work in the past 12 months)*

:::

## Question results: Wellbeing

{{< lipsum 1 random=true >}}

## Question results: Other questions

{{< lipsum 1 random=true >}}

### Civil Service Code

{{< lipsum 1 random=true >}}

### Topical questions

{{< lipsum 1 random=true >}}
